'use strict';

const skills = [
    /* name, isBase, isExpensive, statId */
    ['concentration', true, false, 6],
    ['conceal/reveal object', false, false, 1],
    ['lip reading', false, false, 1],
    ['perception', true, false, 1],
    ['tracking', false, false, 1],
    ['athletics', true, false, 3],
    ['contortionist', false, false, 3],
    ['dance', false, false, 3],
    ['endurance', false, false, 6],
    ['resist torture/drugs', false, false, 6],
    ['stealth', true, false, 3],
    ['drive land vehicle', false, false, 2],
    ['pilot air vehicle', false, true, 2],
    ['pilot sea vehicle', false, false, 2],
    ['riding', false, false, 2],
    ['accounting', false, false, 1],
    ['animal handling', false, false, 1],
    ['bureaucracy', false, false, 1],
    ['business', false, false, 1],
    ['composition', false, false, 1],
    ['criminology', false, false, 1],
    ['cryptography', false, false, 1],
    ['deduction', false, false, 1],
    ['education', true, false, 1],
    ['gamble', false, false, 1],
    ['language 1', true, false, 1], // Streetslang
    ['language 2', false, false, 1],
    ['language 3', false, false, 1],
    ['library search', false, false, 1],
    ['local expert 1', true, false, 1], // Your Home
    ['local expert 2', false, false, 1],
    ['local expert 3', false, false, 1],
    ['science 1', false, false, 1],
    ['science 2', false, false, 1],
    ['tactics', false, false, 1],
    ['wilderness survival', false, false, 1],
    ['brawling', true, false, 3],
    ['evasion', true, false, 3],
    ['martial arts', false, true, 3],
    ['melee weapon', false, false, 3],
    ['acting', false, false, 5],
    ['play instrument 1', false, false, 4],
    ['play instrument 2', false, false, 4],
    ['archery', false, false, 2],
    ['autofire', false, true, 2],
    ['handgun', false, false, 2],
    ['heavy weapons', false, true, 2],
    ['shoulder arms', false, false, 2],
    ['bribery', false, false, 5],
    ['conversation', true, false, 10],
    ['human perception', true, false, 10],
    ['interrogation', false, false, 5],
    ['persuasion', true, false, 5],
    ['personal grooming', false, false, 5],
    ['streetwise', false, false, 5],
    ['trading', false, false, 5],
    ['wardrobe & style', false, false, 5],
    ['air vehicle tech', false, false, 4],
    ['basic tech', false, false, 4],
    ['cybertech', false, false, 4],
    ['demolitions', false, true, 4],
    ['electronics/security tech', false, true, 4],
    ['first aid', true, false, 4],
    ['forgery', false, false, 4],
    ['land vehicle tech', false, false, 4],
    ['paint/draw/sculpt', false, false, 4],
    ['paramedic', false, true, 4],
    ['photography/film', false, false, 4],
    ['pick lock', false, false, 4],
    ['pick pocket', false, false, 4],
    ['sea vehicle tech', false, false, 4],
    ['weaponstech', false, false, 4],
];

/** @type {import('sequelize-cli').Migration} */
module.exports = {
    // eslint-disable-next-line no-unused-vars
    async up(queryInterface, Sequelize) {
        await queryInterface.bulkInsert('Skills', skills.map((s, idx) => ({
            createdAt: new Date(),
            id: idx + 1,
            isBase: s[1],
            isExpensive: s[2],
            name: s[0],
            statisticId: s[3],
            updatedAt: new Date(),
        })));
    },
    // eslint-disable-next-line sort-keys,no-unused-vars
    async down(queryInterface, Sequelize) {
        await queryInterface.bulkDelete('Skills', { id: skills.map((_, idx) => idx + 1) });
    },
};
